version: '3.9'

volumes:
  db-data:

services:
  web:
    build: .
    # railsサーバーを起動させるコマンド
    # command: >
    #   bash -c "rails db:create &&
    #           rails db:migrate &&
    #           rails s -b 0.0.0.0"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - '.:/rails-docker'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    depends_on:
      - db
    tty: true
    stdin_open: true
    links:
      - db
  

  db:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - 'POSGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres' 